---
title: "Données"
---



* [ad_data.txt](donnees/ad_data.txt)  
* [artere.txt](donnees/artere.txt)
* [courbe_lasso.csv](donnees/courbe_lasso.csv)
* [donnees_dd.csv](donnees/dd_donnees.csv)
* [dd_ex_ech_des1.csv](donnees/dd_ex_ech_des1.csv)
* [dd_exo3_1.csv](donnees/dd_exo3_1.csv)
* [dd_exo3_2.csv](donnees/dd_exo3_2.csv)
* [dd_exo3_3.csv](donnees/dd_exo3_3.csv)
* [echan_lasso.csv](donnees/echan_lasso.csv)
* [eucalyptus.txt](donnees/eucalyptus.txt)  
* [lasso_exo8_courbe.csv](donnees/lasso_exo8_courbe.csv)
* [lasso_exo8_echan.csv](donnees/lasso_exo8_echan.csv)
* [logit_donnees.csv](donnees/logit_donnees.csv)
* [logit_ex6.csv](donnees/logit_ex6.csv)
* [logit_ridge_lasso.csv](donnees/logit_ridge_lasso.csv)
* [ozone_complet.txt](donnees/ozone_complet.txt)
* [ozone_long.txt](donnees/ozone_long.txt)
* [ozone_simple.txt](donnees/ozone_simple.txt)
* [ozone_transf.txt](donnees/ozone_transf.txt)
* [ozone.txt](donnees/ozone.txt)
* [panne.txt](donnees/panne.txt)
* [poissonData.csv](donnees/poissonData.csv)
* [poissonData3.csv](donnees/poissonData3.csv)
* [regulglm_exo3.csv](donnees/regulglm_exo3.csv)
* [SAh.csv](donnees/SAh.csv)
* [tpbisrespartiel.dta](donnees/tpbisrespartiel.dta)
* [tprespartiel.dta](donnees/tprespartiel.dta)